# Generated by Django 3.2.19 on 2023-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
