# Generated by Django 3.2.19 on 2023-10-04 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0002_alter_loansession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansession',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='loansession',
            name='loan_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Loaned'),
        ),
    ]
