# Generated by Django 3.2.19 on 2023-10-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0003_auto_20231004_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansession',
            name='loan_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loanmanagement.loanuser'),
            preserve_default=False,
        ),
    ]
