# Generated by Django 3.2.19 on 2023-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0004_loansession_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansession',
            name='loan_date',
            field=models.DateField(verbose_name='Date Loaned'),
        ),
    ]
