# Generated by Django 3.2.19 on 2023-11-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0005_alter_loansession_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
