# Generated by Django 3.2.19 on 2023-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0006_alter_loanuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loansession',
            old_name='stock_item',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='loanuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='loanuser',
            name='restricted',
            field=models.BooleanField(default=False, verbose_name='Restricted'),
        ),
    ]
