# Generated by Django 3.2.19 on 2023-11-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0008_auto_20231115_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanuser',
            name='idn',
            field=models.IntegerField(unique=True, verbose_name='RIN'),
        ),
    ]
