# Generated by Django 3.2.19 on 2023-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0010_auto_20231116_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loansession',
            old_name='date_returned',
            new_name='returned_date',
        ),
        migrations.AlterField(
            model_name='loanuser',
            name='first_name',
            field=models.CharField(default=None, max_length=250, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='loanuser',
            name='last_name',
            field=models.CharField(default=None, max_length=250, verbose_name='Last Name'),
        ),
    ]
