# Generated by Django 3.2.19 on 2024-02-06 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanmanagement', '0011_auto_20231121_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansession',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='loanuser',
            name='email',
            field=models.EmailField(default=None, max_length=20, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='loanuser',
            name='idn',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='RIN'),
        ),
    ]
