# Generated by Django 4.2.12 on 2024-06-04 15:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0110_alter_stockitemtestresult_finished_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(default=None, max_length=250, verbose_name='Last Name')),
                ('email', models.EmailField(default=None, max_length=20, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('idn', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='RIN')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('restricted', models.BooleanField(default=False, verbose_name='Restricted')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Quantity')),
                ('loan_date', models.DateField(verbose_name='Date Loaned')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Location')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('loan_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventree_loan.loanuser')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem')),
            ],
        ),
    ]
