# Generated by Django 4.2.12 on 2024-06-06 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventree_loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansession',
            name='loan_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LoanUser',
        ),
    ]
