# Generated by Django 4.2.15 on 2025-01-17 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventree_loan', '0002_alter_loansession_loan_user_delete_loanuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansession',
            name='loaner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
