# Generated by Django 4.2.15 on 2025-02-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventree_loan', '0004_loansession_last_notice_loansession_notices_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansession',
            name='returned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Returned Date'),
        ),
    ]
